#!/bin/bash

# Windows Auto-Update Diagnostic Script
# This script helps diagnose electron-updater issues

echo "=== Electron-Updater Windows Diagnostic ==="
echo ""

# Check if releases exist
echo "1. Checking GitHub releases structure..."
if [ -d "releases" ]; then
    echo "✅ releases/ folder exists"
    ls -lh releases/
else
    echo "❌ releases/ folder not found"
fi

echo ""
echo "2. Checking for required manifest files..."
echo "   electron-updater requires these files in GitHub releases:"
echo "   - latest.yml (for Windows)"
echo "   - latest-mac.yml (for macOS)"
echo ""

# Check package.json version
echo "3. Current app version:"
CURRENT_VERSION=$(cat package.json | grep '"version"' | head -1 | sed 's/.*: "\(.*\)".*/\1/')
echo "   Version: $CURRENT_VERSION"

echo ""
echo "4. Common electron-updater issues on Windows:"
echo "   ❌ Missing latest.yml manifest file in GitHub release"
echo "   ❌ GitHub release tag doesn't match version in package.json"
echo "   ❌ Asset names don't match expected format"
echo "   ❌ App not properly code-signed (Windows blocks unsigned updates)"
echo "   ❌ Firewall/antivirus blocking electron-updater"

echo ""
echo "5. Required GitHub Release Structure:"
echo "   Release tag: v${CURRENT_VERSION}"
echo "   Required files:"
echo "   - VaultApp-Windows.zip (or .exe installer)"
echo "   - VaultApp-macOS.zip (or .dmg)"
echo "   - latest.yml (generated by electron-builder)"
echo "   - latest-mac.yml (generated by electron-builder)"

echo ""
echo "=== SOLUTION ==="
echo ""
echo "The problem: electron-packager doesn't generate manifest files!"
echo "electron-updater requires manifest files (latest.yml) that only"
echo "electron-builder creates. You're using electron-packager."
echo ""
echo "Option 1: Switch to electron-builder (RECOMMENDED)"
echo "   npm install --save-dev electron-builder"
echo "   Update package.json scripts to use electron-builder"
echo ""
echo "Option 2: Manually create latest.yml"
echo "   See create-update-manifest.sh for template"
echo ""
echo "Option 3: Use custom auto-updater (fallback)"
echo "   Revert to manual GitHub API checking"
echo ""

# Create a sample latest.yml
echo "6. Creating sample latest.yml template..."
cat > latest.yml.template << 'EOF'
version: 1.0.2
files:
  - url: VaultApp-Windows.zip
    sha512: [SHA512_HASH_HERE]
    size: [FILE_SIZE_IN_BYTES]
path: VaultApp-Windows.zip
sha512: [SHA512_HASH_HERE]
releaseDate: '2025-11-01T00:00:00.000Z'
EOF

echo "✅ Created latest.yml.template"
echo ""
echo "To generate SHA512 hash:"
echo "  shasum -a 512 releases/VaultApp-Windows.zip | cut -d ' ' -f 1 | xxd -r -p | base64"
echo ""
echo "=== END DIAGNOSTIC ==="
